import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "../styles/globals.css";
import { Analytics } from '@vercel/analytics/react';
import ScrollObserver from "../utils/scroll-oberver";
import SizeObserver from "../utils/size-observer";
import GoogleAnalytics from './GoogleAnalytics';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SizeObserver>
      <ScrollObserver>
        <html lang="en">
          <body className={inter.className}>
          {process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS ? (
            <GoogleAnalytics ga_id= 
            {process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS} />
          ) : null}
            {children}
            <Analytics />
          </body>
        </html>
      </ScrollObserver>
    </SizeObserver>

  )
}
