import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "../styles/globals.css";
import { Analytics } from '@vercel/analytics/react';
import ScrollObserver from "../utils/scroll-oberver";
import SizeObserver from "../utils/size-observer";
import Script from "next/script";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SizeObserver>
      <ScrollObserver>
        <html lang="en">
          <body className={inter.className}>
            {/* <!-- Google tag (gtag.js) --> */}
            <Script async src="https://www.googletagmanager.com/gtag/js?id=G-VTDSFE7JPH" />
            <Script id='google-analytics' strategy='afterInteractive'>
              {`
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-VTDSFE7JPH');
  `}
            </Script>
            {children}
            <Analytics />
          </body>
        </html>
      </ScrollObserver>
    </SizeObserver>

  )
}
