import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "../styles/globals.css";
import type { AppProps } from "next/app";
import ScrollObserver from "../utils/scroll-oberver";
import SizeObserver from "../utils/size-observer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SizeObserver>
    <ScrollObserver>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
      {/* <Component {...pageProps} /> */}
    </ScrollObserver>
  </SizeObserver>

  )
}
